export const metadata = {
    title: "DM",
    description: "Generated by create next app",
};

export default function DM() {
    return (
        <div>
            <h1>DM</h1>
        </div>
    );
}